[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'h1mesuke/unite-outline'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'deris/vim-shot-f'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'mizukmb/otenki.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'mattn/gist-vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = 'mizukmb/mocho'

[[plugins]]
repo = 'cocopon/Iceberg.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
depends = ['nixprime/cpsm']

[[plugins]]
repo = 'nixprime/cpsm'

[[plugins]]
repo = 'vim-scripts/nginx.vim'
